awakening/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('generales.urls','generales'), namespace='generales')),
    path('',include(('core.urls','core'), namespace='core')),
    path('admin/', admin.site.urls),

]

core/urls.py
from django.urls import path

from core.views import AgenciaView, EmpleadosView, EmpleadosNew, EmpleadosEdit, MotivoNew, Motivosview, MotivoEdit, MotivoDel

urlpatterns = [path('core', AgenciaView.as_view(), name='agencia_list'),

               path('empleado', EmpleadosView.as_view(), name='empleado_list'),
               path('empleado/new', EmpleadosNew.as_view(), name='empleado_new'),
               path('empleado/edit/<int:pk>', EmpleadosEdit.as_view(), name='empleado_edit'),

               # ****************** MANTENIMIENTO DE MOTIVOS *********************
               path('motivo', Motivosview.as_view(), name='rhmotiv_list'),
               path('motivo/new', MotivoNew.as_view(), name='rhmotiv_new'),
               path('motivo/edit/<int:pk>', MotivoEdit.as_view(), name='rhmotiv_edit'),
               path('motivo/delete/<int:pk>', MotivoDel.as_view(), name='rhmotiv_del'),

               ]

generales/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from generales.views import Home, HomeSinPrivilegios
urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='generales/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='generales/login.html'), name='logout'),
    path('sin_privilegios/', HomeSinPrivilegios.as_view(), name='sin_privilegios')
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block head_title %}
            Awg Guatemala
        {% endblock head_title %}
    </title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'base/css/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'base/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'base/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'generales:home' %}">Asociacion Awakening Guatemala</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> {{ user.username }} <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'generales:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="#"><i class="fa fa-cogs fa-fw"></i> Nombre de modulo <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'core:agencia_list' %}">Agencias</a>
                                <a href="{% url 'core:empleado_list' %}">Empleados</a>
                            </li>
                            <li>
                                <a>Recursos Humanos <span class="fa arrow"></span></a>
                                <ul class="nav nav-stacked">
                                    <li>
                                        <a> Parametrizacion <span class="fa arrow"></span> </a>
                                        <ul class="nav nav-second-level">
                                            <li>
                                                <a href="{% url 'core:rhmotiv_list' %}">Mant. de Motivos Suspension/Vacaciones</a>
                                                <a href="{% url 'core:empleado_list' %}">Mant. Academico</a>
                                                <a href="{% url 'core:empleado_list' %}">Mant. Deptos</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <small class="text-danger">
                {% if form.errors %}
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            {{ error|escape }}
                        {% endfor %}
                    {% endif %}
                {% endif %}
            </small>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        <small class="text-danger text-center">
                            {% if messages %}
                                {% for message in messages %}
                                    {{ message|safe }}<br>
                                {% endfor %}
                            {% endif %}
                        </small>
                    </h1>
                    {% block contenido %}Blank{% endblock contenido %}
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="{% static 'base/js/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'base/js/bootstrap.min.js' %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'base/js/metisMenu.min.js' %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static 'base/js/sb-admin-2.js' %}"></script>

</body>

</html>