awakening/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('generales.urls','generales'), namespace='generales')),
    path('',include(('core.urls','core'), namespace='core')),
    path('admin/', admin.site.urls),

]

core/urls.py
from django.urls import path

from core.views import AgenciaView, EmpleadosView, EmpleadosNew, EmpleadosEdit, MotivoNew, Motivosview, MotivoEdit, MotivoDel

urlpatterns = [path('core', AgenciaView.as_view(), name='agencia_list'),

               path('empleado', EmpleadosView.as_view(), name='empleado_list'),
               path('empleado/new', EmpleadosNew.as_view(), name='empleado_new'),
               path('empleado/edit/<int:pk>', EmpleadosEdit.as_view(), name='empleado_edit'),

               # ****************** MANTENIMIENTO DE MOTIVOS *********************
               path('motivo', Motivosview.as_view(), name='rhmotiv_list'),
               path('motivo/new', MotivoNew.as_view(), name='rhmotiv_new'),
               path('motivo/edit/<int:pk>', MotivoEdit.as_view(), name='rhmotiv_edit'),
               path('motivo/delete/<int:pk>', MotivoDel.as_view(), name='rhmotiv_del'),

               ]

core/models.py
from django.db import models

# Create your models here.
class Rhagencia(models.Model):
    agecod = models.IntegerField(primary_key=True)
    agenom = models.CharField(max_length=40, blank=True, null=True)
    direccion = models.CharField(max_length=40, blank=True, null=True)
    def __str__(self):
        return '{}-{}'.format(self.agecod, self.agenom)

    def save(self):
        super(Rhagencia, self).save()

    class Meta:
        verbose_name_plural = "Rhagencia"
        db_table = 'core_Rhagencia'


class Rhempleado(models.Model):
    agecod = models.ForeignKey(Rhagencia, on_delete=models.CASCADE)
    nombres = models.CharField(max_length=100, help_text='Nombres de Empleados')
    apellidos = models.CharField(max_length=100, help_text='Apellidos Empleado')

    def __str__(self):
        return '{}:{}'.format(self.Rhagen.agenom, self.nombres)

    def save(self):
        super(Rhempleado, self).save()

    class Meta:
        verbose_name_plural = 'rhempleados'
        unique_together = ('agecod', 'nombres')
        db_table = 'core_rhempleado'


class Rhmotiv(models.Model):
    codmot = models.IntegerField(primary_key=True, help_text='Id del motivo', unique=True)
    # agecod = models.ForeignKey(Rhagencia, on_delete=models.CASCADE)
    nommot = models.CharField(max_length=100, help_text='Descripcion de Motivo')

    def __str__(self):
        return '{}:{}'.format(self.codmot, self.nommot)

    def save(self):
        super(Rhmotiv, self).save()

    class Meta:
        verbose_name_plural = 'Rhmotiv'
        unique_together = ('codmot', 'nommot')
        db_table = 'core_Rhmotiv'

    class rhacademico(models.Model):
        cod_academico = models.AutoField(primary_key=True, help_text='Id del academico', unique=True)
        # agecod = models.ForeignKey(Rhagencia, on_delete=models.CASCADE)
        desc_academico = models.CharField(max_length=110, help_text='Descripcion de grado Academico', default='')

        # desc_academicod = models.CharField(max_length=2, help_text='Descripcion de grado Academico', default=0)

        def __str__(self):
            return '{}:{}'.format(self.codmot, self.nommot)

        def save(self):
            super(Rhmotiv, self).save()

        class Meta:
            verbose_name_plural = 'rhacademico'
            unique_together = ('cod_academico', 'desc_academico')
            db_table = 'core_rhacademico'

core/forms.py
from django import forms

from core.models import Rhempleado, Rhmotiv


class Empleadoform(forms.ModelForm):
    class Meta:
        model=Rhempleado
        fields=['agecod','nombres','apellidos']
        labels={
            'agecod':'Agencia',
            'nombres':'Nombres',
            'apellidos':'Apellidos'}
        widget={'nombres':forms.TextInput(), 'apellidos':forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['agecod'].empty_label="Seleccione Agencia"


class Rhmotiv_Form(forms.ModelForm):
    class Meta:
        model = Rhmotiv
        fields = ['codmot', 'nommot']
        labels = {
            'codmot': 'Codigo de Motivo',
            'nommot': 'Descripcion de Motivo'}
        widget = {'Cod.': forms.TextInput(), 'Descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        # self.fields['agecod'].empty_label="Seleccione Agencia"

core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from core.models import Rhagencia, Rhempleado, Rhmotiv
from core.forms import Empleadoform, Rhmotiv_Form
from generales.views import SinPrivilegios


# Create your views here.
class AgenciaView(LoginRequiredMixin, generic.ListView):
    model = Rhagencia
    template_name = 'core/agencia_list.html'
    context_object_name = "obj"
    login_url = 'generales:login'


class EmpleadosView(LoginRequiredMixin, generic.ListView):
    model = Rhempleado
    template_name = 'core/empleado_list.html'
    context_object_name = "obj"
    login_url = 'generales:login'


class EmpleadosNew(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios, generic.CreateView):
    permission_required = "core.add_rhempleado"
    model = Rhempleado
    template_name = "core/empleado_form.html"
    context_object_name = 'obj'
    form_class = Empleadoform
    success_url = reverse_lazy("core:empleado_list")
    success_message = "Empleado Creado Satisfactoriamente"


class EmpleadosEdit(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "core.add_rhempleado"
    model = Rhempleado
    template_name = 'core/empleado_form.html'
    context_object_name = 'obj'
    form_class = Empleadoform
    success_url = reverse_lazy("core:empleado_list")
    success_message = "Empleado Actualizado Satisfactoriamente"


# ****************** MANTENIMIENTO DE MOTIVOS *********************
class Motivosview(LoginRequiredMixin, generic.ListView):
    model = Rhmotiv
    template_name = 'core/rhmotiv_list.html'
    context_object_name = "obj"
    login_url = 'generales:login'


class MotivoNew(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios, generic.CreateView):
    permission_required = "core.add_rhmotiv"
    model = Rhmotiv
    template_name = "core/rhmotiv_form.html"
    context_object_name = 'obj'
    form_class = Rhmotiv_Form
    success_url = reverse_lazy("core:rhmotiv_list")
    success_message = "Motivo Creado Satisfactoriamente"


class MotivoEdit(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "core.add_rhmotiv"
    model = Rhmotiv
    template_name = 'core/rhmotiv_form.html'
    context_object_name = 'obj'
    form_class = Rhmotiv_Form
    success_url = reverse_lazy("core:rhmotiv_list")
    success_message = "Motivo Actualizado Satisfactoriamente"


class MotivoDel(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios, generic.DeleteView):
    permission_required = "core.add_rhmotiv"
    model = Rhmotiv
    template_name = "core/rhmotiv_del.html"
    context_object_name = 'obj'
    success_url = reverse_lazy("core:rhmotiv_list")

core/templates/core/agencia_list.html
{% extends 'base/base.html' %}
{% block contenido %}
    <div class="panel panel-primary">
        <div class="panel-body">
            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                <tr>
                    <th>codigo Agencia</th>
                    <th>Agencia</th>
                    <th>Direccion</th>
                </tr>
                </thead>
                <tbody> {% for item in obj %}
                    <tr>
                        <td>{{ item.agecod }}</td>
                        <td>{{ item.agenom }}</td>
                        <td>{{ item.direccion }}</td>
                    </tr> {% endfor %} </tbody>
            </table>
        </div>
    </div>
{% endblock contenido %}

core/templates/core/empleado_form.html
{% extends 'base/base.html' %}

{% block contenido %}
<form method="POST">
    <div class="panel panel-default">
        <div class="panel-heading">
            Editar/Crear Empleados
        </div>
        <div class="panel-body">
             {% csrf_token %}   
             {{ form.as_p }}
            <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Guardar</button>
            <a href="{% url 'core:empleado_list' %}" class="btn btn-danger"><span class="fa fa-undo"></span> Cancelar</a>
        </div> 
    </div>

</form>

{% endblock contenido %}

core/templates/core/empleado_list.html
{% extends 'base/base.html' %}
{% block contenido %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <a href="{% url 'core:empleado_new' %}" class="btn btn-info"><span class="fa fa-plus-circle"></span>
                Nueva</a>
        </div>
        <div class="panel-body">
            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                <tr>
                    <th>codigo Empleado</th>
                    <th>Agencia</th>
                    <th>nombres</th>
                    <th>apellidos</th>
                    <td>Acciones</td>
                </tr>
                </thead>
                <tbody> {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.agecod }}</td>
                        <td>{{ item.nombres }}</td>
                        <td>{{ item.apellidos }}</td>
                        <td>
                            <a href="{% url 'core:empleado_edit' item.id %}" class="btn btn-primary btn-circle"><span class="fa fa-edit"></span></a>
                        </td>
                    </tr> {% endfor %}
                </tbody>
            </table>
        </div>
    </div> {% endblock contenido %}

core/templates/core/rhmotiv_del.html
{% extends 'base/base.html' %}
{% block contenido %}
    <form method="POST">
        <div class="panel panel-default">
            <div class="panel-heading">
                Eliminar
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                {% csrf_token %}
                <div class="alert alert-success">
                    ¿Eliminar {{ obj.nommot }} ?
                </div>
                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Si, Eliminar</button>
                <a href="{% url 'core:rhmotiv_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
            </div>
        </div>
    </form>
{% endblock contenido %}

core/templates/core/rhmotiv_form.html
{% extends 'base/base.html' %}

{% block contenido %}
    <form method="POST">
        <div class="panel panel-default">
            <div class="panel-heading">
                Editar/Crear Motivos
            </div>
            <div class="panel-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Guardar</button>
                <a href="{% url 'core:rhmotiv_list' %}" class="btn btn-danger"><span class="fa fa-undo"></span> Cancelar</a>
            </div>
        </div>
    </form>

{% endblock contenido %}

core/templates/core/rhmotiv_list.html
{% extends 'base/base.html' %}
{% block contenido %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <a href="{% url 'core:rhmotiv_new' %}" class="btn btn-info"><span class="fa fa-plus-circle"></span>
                Nueva</a>
        </div>
        <div class="panel-body">
            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                <tr>
                    <th>Codigo Motivo</th>
                    <th>Descripcion Motivo</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody> {% for item in obj %}
                    <tr>
                        <td>{{ item.codmot }}</td>
                        <td>{{ item.nommot }}</td>
                        <td>
                            <a href="{% url 'core:rhmotiv_edit' item.codmot %}" class="btn btn-primary btn-circle"><span class="fa fa-edit"></span></a>
                            <a href="{% url 'core:rhmotiv_del' item.codmot %}" class="btn btn-danger btn-circle"><span class="fa fa-trash"></span></a>
                        </td>
                    </tr> {% endfor %} </tbody>
            </table>
        </div>
    </div>
{% endblock contenido %}